"""add_announcements_table

Revision ID: 3b8e89d9d9fd
Revises: 003
Create Date: 2026-07-15 06:40:46.995528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b8e89d9d9fd'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='announcement_priority_enum'), server_default='normal', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_author_id'), 'announcements', ['author_id'], unique=False)
    op.create_index(op.f('ix_announcements_created_at'), 'announcements', ['created_at'], unique=False)
    op.create_index(op.f('ix_announcements_is_published'), 'announcements', ['is_published'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_failures', table_name='audit_logs', postgresql_where="((status)::text = 'failure'::text)")
    op.drop_index('idx_audit_logs_resource_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_resource_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_resource_type', table_name='audit_logs')
    op.drop_index('idx_audit_logs_status', table_name='audit_logs')
    op.drop_index('idx_audit_logs_user_action_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.alter_column('email_verification_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('email_verification_tokens', 'verified_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('email_verification_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_email_verification_tokens_expires_at', table_name='email_verification_tokens')
    op.drop_index('idx_email_verification_tokens_token', table_name='email_verification_tokens')
    op.drop_index('idx_email_verification_tokens_user_id', table_name='email_verification_tokens')
    op.drop_constraint('uq_email_verification_tokens_token', 'email_verification_tokens', type_='unique')
    op.create_index(op.f('ix_email_verification_tokens_expires_at'), 'email_verification_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.alter_column('oauth_credentials', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('oauth_credentials', 'last_used',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('oauth_credentials', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oauth_credentials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_oauth_credentials_expires_at', table_name='oauth_credentials')
    op.drop_index('idx_oauth_credentials_is_primary', table_name='oauth_credentials')
    op.drop_index('idx_oauth_credentials_provider', table_name='oauth_credentials')
    op.drop_index('idx_oauth_credentials_provider_user_id', table_name='oauth_credentials')
    op.drop_index('idx_oauth_credentials_user_id', table_name='oauth_credentials')
    op.drop_index('idx_oauth_credentials_user_provider', table_name='oauth_credentials')
    op.drop_constraint('uq_oauth_provider_user', 'oauth_credentials', type_='unique')
    op.create_index(op.f('ix_oauth_credentials_expires_at'), 'oauth_credentials', ['expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_credentials_is_primary'), 'oauth_credentials', ['is_primary'], unique=False)
    op.create_index(op.f('ix_oauth_credentials_provider'), 'oauth_credentials', ['provider'], unique=False)
    op.create_index(op.f('ix_oauth_credentials_user_id'), 'oauth_credentials', ['user_id'], unique=False)
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_password_reset_tokens_expires_at', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_tokens_token', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_tokens_user_id', table_name='password_reset_tokens')
    op.drop_constraint('uq_password_reset_tokens_token', 'password_reset_tokens', type_='unique')
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.alter_column('users', 'email_verified_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'account_locked_until',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'last_password_change',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_users_active_verified', table_name='users', postgresql_where='((is_active = true) AND (is_verified = true))')
    op.drop_index('idx_users_apple_id', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_github_id', table_name='users')
    op.drop_index('idx_users_google_id', table_name='users')
    op.drop_index('idx_users_house_number', table_name='users')
    op.drop_index('idx_users_ic_number', table_name='users')
    op.drop_index('idx_users_is_verified', table_name='users')
    op.drop_index('idx_users_locked', table_name='users', postgresql_where='(account_locked_until IS NOT NULL)')
    op.drop_index('idx_users_microsoft_id', table_name='users')
    op.drop_index('idx_users_phone_number', table_name='users')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_index('idx_users_taman_name', table_name='users')
    op.drop_index('idx_users_updated_at', table_name='users')
    op.drop_index('idx_users_verification_status', table_name='users')
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_constraint('uq_users_ic_number', 'users', type_='unique')
    op.create_index(op.f('ix_users_apple_id'), 'users', ['apple_id'], unique=True)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_house_number'), 'users', ['house_number'], unique=False)
    op.create_index(op.f('ix_users_ic_number'), 'users', ['ic_number'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_verified'), 'users', ['is_verified'], unique=False)
    op.create_index(op.f('ix_users_microsoft_id'), 'users', ['microsoft_id'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_taman_name'), 'users', ['taman_name'], unique=False)
    op.create_index(op.f('ix_users_verification_status'), 'users', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_verification_status'), table_name='users')
    op.drop_index(op.f('ix_users_taman_name'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_microsoft_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_verified'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_ic_number'), table_name='users')
    op.drop_index(op.f('ix_users_house_number'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_apple_id'), table_name='users')
    op.create_unique_constraint('uq_users_ic_number', 'users', ['ic_number'])
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.create_index('idx_users_verification_status', 'users', ['verification_status'], unique=False)
    op.create_index('idx_users_updated_at', 'users', ['updated_at'], unique=False)
    op.create_index('idx_users_taman_name', 'users', ['taman_name'], unique=False)
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_index('idx_users_phone_number', 'users', ['phone_number'], unique=False)
    op.create_index('idx_users_microsoft_id', 'users', ['microsoft_id'], unique=True)
    op.create_index('idx_users_locked', 'users', ['account_locked_until'], unique=False, postgresql_where='(account_locked_until IS NOT NULL)')
    op.create_index('idx_users_is_verified', 'users', ['is_verified'], unique=False)
    op.create_index('idx_users_ic_number', 'users', ['ic_number'], unique=True)
    op.create_index('idx_users_house_number', 'users', ['house_number'], unique=False)
    op.create_index('idx_users_google_id', 'users', ['google_id'], unique=True)
    op.create_index('idx_users_github_id', 'users', ['github_id'], unique=True)
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_apple_id', 'users', ['apple_id'], unique=True)
    op.create_index('idx_users_active_verified', 'users', ['is_active', 'is_verified'], unique=False, postgresql_where='((is_active = true) AND (is_verified = true))')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'last_password_change',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'account_locked_until',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'email_verified_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.create_unique_constraint('uq_password_reset_tokens_token', 'password_reset_tokens', ['token'])
    op.create_index('idx_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index('idx_password_reset_tokens_token', 'password_reset_tokens', ['token'], unique=True)
    op.create_index('idx_password_reset_tokens_expires_at', 'password_reset_tokens', ['expires_at'], unique=False)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('password_reset_tokens', 'used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_oauth_credentials_user_id'), table_name='oauth_credentials')
    op.drop_index(op.f('ix_oauth_credentials_provider'), table_name='oauth_credentials')
    op.drop_index(op.f('ix_oauth_credentials_is_primary'), table_name='oauth_credentials')
    op.drop_index(op.f('ix_oauth_credentials_expires_at'), table_name='oauth_credentials')
    op.create_unique_constraint('uq_oauth_provider_user', 'oauth_credentials', ['provider', 'provider_user_id'])
    op.create_index('idx_oauth_credentials_user_provider', 'oauth_credentials', ['user_id', 'provider'], unique=False)
    op.create_index('idx_oauth_credentials_user_id', 'oauth_credentials', ['user_id'], unique=False)
    op.create_index('idx_oauth_credentials_provider_user_id', 'oauth_credentials', ['provider', 'provider_user_id'], unique=True)
    op.create_index('idx_oauth_credentials_provider', 'oauth_credentials', ['provider'], unique=False)
    op.create_index('idx_oauth_credentials_is_primary', 'oauth_credentials', ['is_primary'], unique=False)
    op.create_index('idx_oauth_credentials_expires_at', 'oauth_credentials', ['expires_at'], unique=False)
    op.alter_column('oauth_credentials', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oauth_credentials', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oauth_credentials', 'last_used',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('oauth_credentials', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_expires_at'), table_name='email_verification_tokens')
    op.create_unique_constraint('uq_email_verification_tokens_token', 'email_verification_tokens', ['token'])
    op.create_index('idx_email_verification_tokens_user_id', 'email_verification_tokens', ['user_id'], unique=False)
    op.create_index('idx_email_verification_tokens_token', 'email_verification_tokens', ['token'], unique=True)
    op.create_index('idx_email_verification_tokens_expires_at', 'email_verification_tokens', ['expires_at'], unique=False)
    op.alter_column('email_verification_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_verification_tokens', 'verified_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('email_verification_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_logs_user_action_created', 'audit_logs', ['user_id', 'action', 'created_at'], unique=False)
    op.create_index('idx_audit_logs_status', 'audit_logs', ['status'], unique=False)
    op.create_index('idx_audit_logs_resource_type', 'audit_logs', ['resource_type'], unique=False)
    op.create_index('idx_audit_logs_resource_id', 'audit_logs', ['resource_id'], unique=False)
    op.create_index('idx_audit_logs_resource_created', 'audit_logs', ['resource_type', 'resource_id', 'created_at'], unique=False)
    op.create_index('idx_audit_logs_failures', 'audit_logs', ['created_at', 'user_id'], unique=False, postgresql_where="((status)::text = 'failure'::text)")
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_announcements_is_published'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_created_at'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_author_id'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
