"""update_resident_types

Revision ID: 48be56ec9d10
Revises: 3b8e89d9d9fd
Create Date: 2026-07-15 06:48:16.490792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48be56ec9d10'
down_revision = '3b8e89d9d9fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    resident_type_enum = sa.Enum('owner', 'tenant', name='resident_type_enum')
    resident_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('resident_type', resident_type_enum, nullable=True))
    op.add_column('users', sa.Column('committee_title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###

    # Safely update user_role_enum to remove 'guest'
    op.execute("UPDATE users SET role = 'resident' WHERE role = 'guest'")
    op.execute("ALTER TYPE user_role_enum RENAME TO user_role_enum_old")
    op.execute("CREATE TYPE user_role_enum AS ENUM ('admin', 'resident')")
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE user_role_enum USING role::text::user_role_enum")
    op.execute("ALTER TABLE users ALTER COLUMN role SET DEFAULT 'resident'")
    op.execute("DROP TYPE user_role_enum_old")


def downgrade() -> None:
    # Reverse the enum migration
    op.execute("ALTER TYPE user_role_enum RENAME TO user_role_enum_old")
    op.execute("CREATE TYPE user_role_enum AS ENUM ('admin', 'resident', 'guest')")
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE user_role_enum USING role::text::user_role_enum")
    op.execute("ALTER TABLE users ALTER COLUMN role SET DEFAULT 'guest'")
    op.execute("DROP TYPE user_role_enum_old")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'committee_title')
    op.drop_column('users', 'resident_type')
    op.execute("DROP TYPE resident_type_enum")
    # ### end Alembic commands ###
