"""add passport_number

Revision ID: 4e28d87fb4fb
Revises: 48be56ec9d10
Create Date: 2026-07-15 07:18:20.060496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e28d87fb4fb'
down_revision = '48be56ec9d10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passport_number', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_passport_number'), 'users', ['passport_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_passport_number'), table_name='users')
    op.drop_column('users', 'passport_number')
    # ### end Alembic commands ###
